# SPDX-FileCopyrightText: 2022 George Florea Bănuș <georgefb899@gmail.com>
# SPDX-License-Identifier: CC0-1.0

include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-reuse.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd.yml
